# -*- coding: utf-8 -*-
"""Day3_python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osQS9yOhA-wOjboBkeNnsszJUb-1O-YZ
"""

""" string = it is a sequence of character which is enclosed in a single or double quotes it can be a character , word , sentences
written inside a single or double quotes whether it has a meaning or not it does not matter if it is written inside the single or double quotes
then it will called a string

note = even if number , floating data is written inside a single or doubles quotes then it is also a string
examples....."""

name = "radha"
or_name = 'krishna'
num = "57"
dec = '98'
print(type(name))
print(type(or_name))
print(type(num))
print(type(dec))



"""strings method
method 1 = .strip()   -----> means cut the space
method 2 = .upper()     -----> make capitals either it character or word or sentence
method 3 = .lower()       -----> make small either it character or word or sentence
method 4 = .replace("tell the word which you want to replace" , "the word you want to add at place of older one")
method 5 = .find("tell the word that you want to find ")       -----> it give the index number of the word you want to find
method 6 = .len("variable")      ----->  it give the lenght of the string including the space between the strings .


syntax for applying these methods = variable.method()


lets practice based on these strings methods """

a = "radha krishna"
print(a.strip())
print(name.upper())
print(name.lower())
print(name.replace("radha","devotee"))
print(name.find("a"))
print(len(name))




""" list = it is a type of container that stores multiple data types in a single variable and list is created by []
         1) list is ordered
         2) list is changeable(mutable)
         3) list allows duplicates values


  examples....."""

skill = ["python" ,"ai" ,"ml" ,"data science"]
print(skill)
print(skill[0])

""" how can  i change the  data of tuple ...
syntax...
variable[indexing number that you want to change the particular value] = "new value" """

skill[0] = "java"
print(skill)



""" list and its method
variable.method()
your method can be = .append(x) = it add the lasst item in the list
. insert(i , x) = it add the value at i index
 .sort()  = it convert the list into ascending order
.clear() = it clear or empty the the list
 .reverse() = it reverse the whole list value
.pop() = it removes the last item



note = if you change the list values by method it will change the values but it doesn't show any output as output returns none """

print(skill.append("mango"))
print(skill.insert(2,"c++"))
print(skill.sort())
print(skill.reverse())




"""tuple = tuples is as same as list but there is only difference is tuple not mutable(changable) , it is immutable. """


vegetable = ("tomato" , "onion" , "potato" , "tomato")

print(vegetable)


"""tuples method
variable.count(x)  -------------> it tells the number of times the value is repeated
variable.index(x)   -------> it tells the index number of the value where it comes first  """


print(vegetable.count("tomato"))
print(vegetable.index("tomato"))